global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-jmx-exporter'
    static_configs:
      - targets: ['broker:7071']  # Point to Kafka's JMX Exporter